<a href="https://colab.research.google.com/github/nikhil00shinde/ml/blob/main/Data_Manipulation_with_Pandas_(2_Aggregating_DataFrames).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Summary Statistics

In [50]:
import pandas as pd
df = pd.DataFrame({
    'name':['john','mary','peter','jeff','bill','lisa','jose'],
    'age':[23,78,22,19,45,33,20],
    'gender':['M','F','M','M','M','F','M'],
    'salary'  : [50000,52000,56000,62000,37000,45000,52000]
})

In [6]:
df['age'].mean() # .median(), .mode(), .min(), .max(), .var(), .std(), .sum()

np.float64(34.285714285714285)

In [11]:
## .agg() --> The .agg() method allows you to apply your own custom functions to a DataFrame, as well as apply functions to more than one column of a DataFrame at once, making your aggregations super-efficient.
def pct30(column):
  return column.quantile(0.3)

def pct40(column):
  return column.quantile(0.4)

df['age_pct30'] = df['age'].agg(pct30)

## More than one column
df[['age', 'age_pct30']].agg(pct30)
df[['age', 'age_pct30']].agg([pct30,pct40,"median"])

        age  age_pct30
pct30  21.6       21.6
pct40  22.4       21.6

In [14]:
df['age'].cumsum() ## Like prefix sum
## .cumsum(), .cummin(), .cumprod()

0     23
1    101
2    123
3    142
4    187
5    220
6    240
Name: age, dtype: int64

## Counting

In [18]:
print(df)
print(df.drop_duplicates(subset=['gender','name'])) # Get unique name and with gender

    name  age gender  age_pct30
0   john   23      M       21.6
1   mary   78      F       21.6
2  peter   22      M       21.6
3   jeff   19      M       21.6
4   bill   45      M       21.6
5   lisa   33      F       21.6
6   jose   20      M       21.6
    name  age gender  age_pct30
0   john   23      M       21.6
1   mary   78      F       21.6
2  peter   22      M       21.6
3   jeff   19      M       21.6
4   bill   45      M       21.6
5   lisa   33      F       21.6
6   jose   20      M       21.6

In [27]:
# count the value of each gender and also we can sort
print(df['gender'].value_counts(sort=True))

# Get proportion
print(df[['gender']].value_counts(normalize=True))

gender
M    5
F    2
Name: count, dtype: int64
gender
M         0.714286
F         0.285714
Name: proportion, dtype: float64

In [42]:
## Summaries by group
# df[df['age'] >= 30]
# df[df['age'] >= 50]['age'].mean()



# ## EASY WAY
df.groupby('gender')['age'].mean()

## Multiple grouped summaries
df.groupby('gender')['age'].agg([min,max,sum])


## Group by multiple multiple variables
df.groupby(['gender','age'])['age'].mean()

/tmp/ipython-input-4085929759.py:11: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('gender')['age'].agg([min,max,sum])
/tmp/ipython-input-4085929759.py:11: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('gender')['age'].agg([min,max,sum])
/tmp/ipython-input-4085929759.py:11: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('gender')['age'].agg([min,max,sum])

gender  age
F       33     33.0
        78     78.0
M       19     19.0
        20     20.0
        22     22.0
        23     23.0
        45     45.0
Name: age, dtype: float64

## Pivot Tables

In [53]:
# same as groupby, default mean

# dogs.groupby('color')['weight_kg'].mean()

# dogs.pivot_table(values='weight_kg',index='color')


df.pivot_table(values='age',index='gender')

df.pivot_table(values='age',index='gender',aggfunc=['mean','median'])




# Pivot on two variables
df.pivot_table(values='age',index='gender',columns='salary',fill_value=0,margins=True)

salary  37000  45000  50000  52000  56000  62000        All
gender
F         0.0   33.0    0.0   78.0    0.0    0.0  55.500000
M        45.0    0.0   23.0   20.0   22.0   19.0  25.800000
All      45.0   33.0   23.0   49.0   22.0   19.0  34.285714